services:
  nginx:
    image: nginx:1.27.0-bookworm
    ports:
      - ${APP_PORT}:80
    volumes:
      - .:/var/www/html
      - ./devops/local/nginx/default.conf:/etc/nginx/conf.d/default.conf

  php:
    build:
      dockerfile: devops/local/php/normal/Dockerfile
      context: .
    user: ${CURRENT_UID}
    environment:
      - XDG_CONFIG_HOME=/var/www/html/.config
    volumes:
      - .:/var/www/html
      - ./devops/local/php/normal/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./devops/local/php/normal/opcache.ini:/usr/local/etc/php/conf.d/docker-php-ext-opcache.ini
  mysql:
    image: mysql:8.0
    ports:
      - 3397:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    volumes:
      - ./docker_data/mysql:/var/lib/mysql
      - ./devops/local/mysql:/var/mysql

  redis:
    image: redis:7.2.2
    ports:
      - 6391:6379
    command: redis-server --save "" --appendonly no
    deploy:
      restart_policy:
        condition: any
    volumes:
      - ./docker_data/redis:/data